package ORM;
// Generated 25 nov. 2020 23:16:29 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private String dni;
	private String nomEmp;
	private EmpPlantilla empPlantilla;
	private Set asigProyectos = new HashSet(0);
	private DatosProf datosProf;

	public Empleado() {
	}

	public Empleado(String dni, String nomEmp) {
		this.dni = dni;
		this.nomEmp = nomEmp;
	}

	public Empleado(String dni, String nomEmp, EmpPlantilla empPlantilla, Set asigProyectos, DatosProf datosProf) {
		this.dni = dni;
		this.nomEmp = nomEmp;
		this.empPlantilla = empPlantilla;
		this.asigProyectos = asigProyectos;
		this.datosProf = datosProf;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getNomEmp() {
		return this.nomEmp;
	}

	public void setNomEmp(String nomEmp) {
		this.nomEmp = nomEmp;
	}

	public EmpPlantilla getEmpPlantilla() {
		return this.empPlantilla;
	}

	public void setEmpPlantilla(EmpPlantilla empPlantilla) {
		this.empPlantilla = empPlantilla;
	}

	public Set getAsigProyectos() {
		return this.asigProyectos;
	}

	public void setAsigProyectos(Set asigProyectos) {
		this.asigProyectos = asigProyectos;
	}

	public DatosProf getDatosProf() {
		return this.datosProf;
	}

	public void setDatosProf(DatosProf datosProf) {
		this.datosProf = datosProf;
	}

}
