package ORM;
// Generated 25 nov. 2020 23:16:29 by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * EmpPlantilla generated by hbm2java
 */
public class EmpPlantilla implements java.io.Serializable {

	private String dni;
	private Empleado empleado;
	private Integer numEmp;
	private Set proyectos = new HashSet(0);

	public EmpPlantilla() {
	}

	public EmpPlantilla(Empleado empleado) {
		this.empleado = empleado;
	}

	public EmpPlantilla(Empleado empleado, Integer numEmp, Set proyectos) {
		this.empleado = empleado;
		this.numEmp = numEmp;
		this.proyectos = proyectos;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Integer getNumEmp() {
		return this.numEmp;
	}

	public void setNumEmp(Integer numEmp) {
		this.numEmp = numEmp;
	}

	public Set getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Set proyectos) {
		this.proyectos = proyectos;
	}

}
